apiVersion: v1
kind: Service
metadata:
  name: pet-clinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: pet-clinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
        - name: pet-clinic
          image: 117134819170.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:2
          ports:
            - containerPort: 8080